SUPABASE_URL = "https://xmafxwjwizaomwglooaa.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtYWZ4d2p3aXphb213Z2xvb2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3ODIzOTMsImV4cCI6MjA4MzM1ODM5M30.NrRfLuZc2qPIhnP6tPUqIpGov9M9xfX31ql7U1efwYs"
